SYSTARG=Linux
<$ROOT/mkconfig
SYSTARG=Linux

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=

# GUI Backend Selection
# Options: headless, sdl3
# Default: headless (no display, terminal only)
GUIBACK=headless

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters


<| $SHELLNAME ../port/mkdevlist  $CONF	#sets $IP, $DEVS, $PORT, $LIBS
<mkfile-$OBJTYPE	# sets $ARCHFILES

# Include GUI backend configuration
<mkfile-gui-$GUIBACK

OBJ=\
	asm-$OBJTYPE.$O\
	$ARCHFILES\
	os.$O\
	kproc-pthreads.$O\
	segflush-$OBJTYPE.$O\
	$GUISRC\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

#LIBNAMES=${LIBS:%=lib%.a}
#libs=${LIBS:%=$ROOT/$OBJDIR/lib/lib%.a}

HFILES=\

CFLAGS=\
	'-DROOT="'$ROOT'"'\
	-DEMU -I. -I../port\
	-I$ROOT/$SYSTARG/$OBJTYPE/include\
	-I$ROOT/include\
	-I$ROOT/libinterp\
	$CTHREADFLAGS $CFLAGS $EMUOPTIONS $GUIFLAGS\

KERNDATE=`{$NDATE}

SYSLIBS=\
	-lm\
	-lX11\
	-lXext\
	-lpthread\

default:V:	$O.$CONF

$O.$CONF:	$OBJ $CONF.c $CONF.root.h # $LIBNAMES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS $GUILIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

<../port/portmkfile

devfs.$O:	../port/devfs-posix.c
