#!/dis/sh.dis
# emu sh initialisation
load std

echo 'PROFILE LOADING...'

# Set command search path FIRST
path=(/dis .)

# Get username
user="{cat /dev/user}
home=/usr/^$user

# Mount namespace generator (must run in background - it's a server)
mount -ac {mntgen} /n &

# Mount host filesystem to /n/local (also runs as server)
if {~ $emuhost MacOSX Linux}{
	mkdir -p /n/local
	trfs '#U*' /n/local &
	# Give servers time to start
	sleep 1
	# Get actual HOME from host
	ghome=/n/local/^`{echo 'echo $HOME' | os sh}
	home=$ghome
}

# Create tmp directory if needed
if {! ftest -d $home/tmp} {
	mkdir -p $home/tmp
}

# Bind tmp to /tmp so applications can find it
bind -bc $home/tmp /tmp

# Change to home directory
cd $home
