<$ROOT/mkconfig

DIRS=\
	testing\

TARG=\
	9p_export_test.dis\
	example_test.dis\
	hello_test.dis\
	runner.dis\
	sdl3_test.dis\
	stderr_test.dis\
	tcp_test.dis\
	tempfile_test.dis\

MODULES=

SYSMODULES=\
	arg.m\
	draw.m\
	readdir.m\
	sh.m\
	sys.m\
	testing.m\

DISBIN=$ROOT/dis/tests

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
