<$ROOT/mkconfig

DIRS=\
	testing\

TARG=\
	9p_export_test.dis\
	agent_test.dis\
	asyncio_test.dis\
	crypto_test.dis\
	edit_test.dis\
	example_test.dis\
	hello_test.dis\
	jit_test.dis\
	runner.dis\
	sdl3_test.dis\
	spawn_test.dis\
	ssl_transport_test.dis\
	stderr_test.dis\
	tcp_test.dis\
	tempfile_test.dis\
	tls_crypto_test.dis\
	tls_live_test.dis\
	tls_protocol_test.dis\
	webclient_test.dis\
	veltro_concurrent_test.dis\
	veltro_security_test.dis\
	veltro_test.dis\
	veltro_tools_test.dis\
	xenith_concurrency_test.dis\
	xenith_exit_test.dis\

MODULES=

SYSMODULES=\
	arg.m\
	bufio.m\
	draw.m\
	keyring.m\
	nsconstruct.m\
	readdir.m\
	security.m\
	sh.m\
	sys.m\
	testing.m\
	tls.m\
	webclient.m\

DISBIN=$ROOT/dis/tests

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
