<$ROOT/mkconfig

TARG=\
	rlayout.dis\
	imgrender.dis\
	mdrender.dis\
	htmlrender.dis\
	pdfrender.dis\

MODULES=\
	rlayout.m\

SYSMODULES=\
	sys.m\
	draw.m\
	html.m\
	filter.m\
	renderer.m\

DISBIN=$ROOT/dis/xenith/render

all:V:	$TARG

<$ROOT/mkfiles/mkdis

install:V:	$BINTARG

nuke:V:
	rm -f *.dis *.sbl

clean:V:
	rm -f *.dis *.sbl
