<../../../mkconfig

TARG=\
	clone.dis\
	diff.dis\
	fetch.dis\
	fs.dis\
	log.dis\
	pull.dis\
	status.dis\

MODULES=

SYSMODULES=\
	arg.m\
	bufio.m\
	draw.m\
	git.m\
	keyring.m\
	styx.m\
	string.m\
	styxservers.m\
	sys.m\

DISBIN=$ROOT/dis/cmd/git

<$ROOT/mkfiles/mkdis
